### ISSUE TITLE
error running bundle install

### ISSUE THREAD

**Issue by wtholliday** [middlemac/middlemac#3]
I'm on macOS 10.15.5.

When running bundle install, I get:

```
% bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32`.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    middleman (~> 4.2.0) was resolved to 4.2.0, which depends on
      middleman-core (= 4.2.0) was resolved to 4.2.0, which depends on
        bundler (~> 1.1)

  Current Bundler version:
    bundler (2.1.4)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
```

I tried following instructions [here](https://stackoverflow.com/a/12093575/682466):

```
% sudo gem install bundler -v '~> 1.1.0'
Fetching bundler-1.1.5.gem
Successfully installed bundler-1.1.5
Parsing documentation for bundler-1.1.5
Installing ri documentation for bundler-1.1.5
Done installing documentation for bundler after 1 seconds
1 gem installed
% bundle _1.1.5_ install            
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rubygems/format (LoadError)
       /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
       /Library/Ruby/Gems/2.6.0/gems/bundler-1.1.5/lib/bundler/source.rb:5:in `<top (required)>'
       /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
       /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
       /Library/Ruby/Gems/2.6.0/gems/bundler-1.1.5/lib/bundler/dsl.rb:19:in `initialize'
       /Library/Ruby/Gems/2.6.0/gems/bundler-1.1.5/lib/bundler/dsl.rb:6:in `new'
       /Library/Ruby/Gems/2.6.0/gems/bundler-1.1.5/lib/bundler/dsl.rb:6:in `evaluate'
       /Library/Ruby/Gems/2.6.0/gems/bundler-1.1.5/lib/bundler/definition.rb:18:in `build'
       /Library/Ruby/Gems/2.6.0/gems/bundler-1.1.5/lib/bundler.rb:135:in `definition'
       /Library/Ruby/Gems/2.6.0/gems/bundler-1.1.5/lib/bundler/cli.rb:220:in `install'
       /Library/Ruby/Gems/2.6.0/gems/bundler-1.1.5/lib/bundler/vendor/thor/task.rb:22:in `run'
       /Library/Ruby/Gems/2.6.0/gems/bundler-1.1.5/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
       /Library/Ruby/Gems/2.6.0/gems/bundler-1.1.5/lib/bundler/vendor/thor.rb:263:in `dispatch'
       /Library/Ruby/Gems/2.6.0/gems/bundler-1.1.5/lib/bundler/vendor/thor/base.rb:386:in `start'
       /Library/Ruby/Gems/2.6.0/gems/bundler-1.1.5/bin/bundle:13:in `<top (required)>'
       /usr/local/bin/bundle:23:in `load'
       /usr/local/bin/bundle:23:in `<main>'
There was an error in your Gemfile, and Bundler cannot continue.
```

**Comment by balthisar** [comment]
Oops, sorry for the long delay in responding. I'm not sure why I didn't get an automatic notification.

It looks like a newer version of Ruby forced a really new version of Bundler on things. I'll fix this right now, and push an update in a bit.
